---
generation: 
  method: online_store
  version: "0.1"
  sources: 
    theme_settings: config/settings_schema.json
  includes: 
    - "**/*.json"
    - "**/*.liquid"
    - "**/*.css"
    - "**/*.js"
  requires: 
    - file_uploads: false
    - user_assets: false
    - subscriptions: false
    - all_files: false
    - password_page: true
    - cart: true
    - layout: true
    - templates: all
    - grids: false
    - blogs: false
    - articles: false
    - pages: false
    - products: true
    - collections: true
    - blog_posts: false
    - navigation: true
    - translation_keys: true
    - valid_settings: true
    - sections: true
  assets: 
    - name: global.js
      file: "assets/global.js"
      src: "assets/global.js"
    - name: section-flash-deal.css
      file: "assets/section-flash-deal.css"
      src: "assets/section-flash-deal.css"
  templates: 
    - name: index
      file: templates/index.json
    - name: product
      file: templates/product.json
    - name: collection
      file: templates/collection.json
    - name: list-collections
      file: templates/list-collections.json
    - name: page
      file: templates/page.json
    - name: search
      file: templates/search.json
    - name: cart
      file: templates/cart.json
    - name: 404
      file: templates/404.json
    - name: customers/account
      file: templates/customers/account.json
    - name: customers/activate_account
      file: templates/customers/activate_account.json
    - name: customers/addresses
      file: templates/customers/addresses.json
    - name: customers/login
      file: templates/customers/login.json
    - name: customers/order
      file: templates/customers/order.json
    - name: customers/register
      file: templates/customers/register.json
    - name: customers/reset_password
      file: templates/customers/reset_password.json
  section_names: 
    - announcement-bar
    - header
    - footer
    - flash-deal-hero
    - featured-collection
  translations:
    - file: locales/en.default.json
      language: en
    - file: locales/en.json
      language: en
  publish:
    name: XD IPX Flash Deals
    preview_url: "{{preview_url}}"
    ready: false